package com.adeeb.taskflow.taskflow_service.config;

import com.adeeb.taskflow.taskflow_service.entity.Task;
import com.adeeb.taskflow.taskflow_service.enums.TaskStatus;
import com.adeeb.taskflow.taskflow_service.repository.TaskRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;

@Configuration
public class DataInitializer {

    @Bean
    public CommandLineRunner loadSampleTasks(TaskRepository taskRepository) {

        return args -> {

            if (taskRepository.count() == 0) {

                Task task1 = new Task();
                task1.setTitle("Complete Wellness360 Assignment");
                task1.setDescription("This task is generated by backend for faster testing by reviewer.");
                task1.setDueDate(LocalDate.now().plusDays(3));
                task1.setStatus(TaskStatus.IN_PROGRESS);

                Task task2 = new Task();
                task2.setTitle("Learn Spring boot");
                task2.setDescription("This task is generated by backend for faster testing by reviewer.");
                task2.setDueDate(LocalDate.now().plusDays(5));
                task2.setStatus(TaskStatus.PENDING);

                Task task3 = new Task();
                task3.setTitle("Write Unit Tests");
                task3.setDescription("This task is generated by backend for faster testing by reviewer.");
                task3.setDueDate(LocalDate.now().plusDays(2));
                task3.setStatus(TaskStatus.COMPLETED);

                Task task4 = new Task();
                task4.setTitle("Prepare README");
                task4.setDescription("This task is generated by backend for faster testing by reviewer.");
                task4.setDueDate(LocalDate.now().plusDays(1));
                task4.setStatus(TaskStatus.PENDING);

                taskRepository.save(task1);
                taskRepository.save(task2);
                taskRepository.save(task3);
                taskRepository.save(task4);
            }
        };
    }
}